version: "3.9"

services:
  backend_app:
    build: .
    container_name: backend-lab-7
    ports:
      - "4000:3000"      # порт Node.js
      - "9229:9229"      # порт для дебагу
    depends_on:
      - backend_db
    environment:
      HOST: "0.0.0.0"
      PORT: ${PORT:-3000}
      DB_HOST: backend_db
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-rootpassword}
      DB_NAME: ${DB_NAME:-inventorydb}
      CACHE_DIR: ${CACHE_DIR:-/app/cache}
    volumes:
      - ./:/app
      - /app/node_modules
      - app_cache:/app/cache
    command: npm run dev

  backend_db:
    image: mysql:8.0
    container_name: mysql-db-7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-inventorydb}
    ports:
      - "3307:3306"     # щоб не конфліктував з локальним MySQL
    volumes:
      - db_data:/var/lib/mysql

volumes:
  app_cache:
  db_data:
